# Generated by Django 3.0 on 2019-12-06 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productattribute_productprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='price_date',
        ),
        migrations.AddField(
            model_name='productprice',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
